export const CONTACTUS_GETALL_REQUEST = 'CONTACTUS_GETALL_REQUEST'
export const CONTACTUS_GETALL_SUCCESS = 'CONTACTUS_GETALL_SUCCESS'
export const CONTACTUS_GETALL_FAILURE = 'CONTACTUS_GETALL_FAILURE'

export const CREATE_DATA_REQUEST = 'CREATE_DATA_REQUEST'
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS'
export const CREATE_DATA_FAILURE = 'CREATE_DATA_FAILURE'