export const CONTACTUS_GETALL_REQUEST = 'CONTACTUS_GETALL_REQUEST'
export const CONTACTUS_GETALL_SUCCESS = 'CONTACTUS_GETALL_SUCCESS'
export const CONTACTUS_GETALL_FAILURE = 'CONTACTUS_GETALL_FAILURE'